# -*- coding: utf-8 -*-
"""multivariantLinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uR0eUCapzCygeU8oVhpMY8aVc9B9SimS
"""

import numpy as np
import pandas as pd
from sklearn import linear_model

df = pd.read_excel('/content/drive/MyDrive/ML_Module_3/AdvertisingSpendvsSales.xlsx')
df

x = df[['TV', 'radio', 'newspaper']]
y = df['sales']

from sklearn import model_selection
x_train, x_test, y_train, y_test = model_selection.train_test_split(x, y, test_size=0.2)

len(x_test)

from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(x_train, y_train)

lr.predict(x_test)

lr.score(x_test, y_test)

y_test